apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otlp-gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otlp-gateway
  endpoints:
    - port: metrics
      scheme: http