apiVersion: dip.io/v1alpha1
kind: Postgres
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-1"
spec:

{{- if .Values.database.cnpg }}
  crossplane:
    compositionSelector:
      matchLabels:
        provider: cnpg
{{- end }}

  parameters:
    identifier: {{ .Values.environmentConfig.resourcePrefix }}-grafana
    size: small
    engineVersion: "18.1"
    databaseName: grafana
    masterUsername: grafana
  {{- if and .Values.database.cnpg .Values.database.snapshots.enabled }}
    enableSnapshots: true
    snapshotClassName: {{ .Values.database.snapshots.snapshotClassName | quote }}
    storageClassName: {{ .Values.database.snapshots.storageClassName | quote }}
  {{- end }}
  {{- if and .Values.database.cnpg .Values.database.restoreFromVolumeSnapshot.enabled }}
    storageClassName: {{ .Values.database.restoreFromVolumeSnapshot.storageClassName | quote }}
    restore:
      method: volumeSnapshot
      sourceIdentifier: {{ .Values.database.restoreFromVolumeSnapshot.sourceIdentifier | quote }}
  {{- else if .Values.database.restoreFromSnapshot }}
    restore:
      snapshotIdentifier: {{ .Values.database.snapshotId }}
  {{- end }}
  writeConnectionSecretToRef:
    name: grafana-postgres-connection