{{- if .Values.grafana.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana-httproute
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  parentRefs:
    - name: {{ .Values.grafana.httpRoute.sharedGatewayName }}
      namespace: {{ .Values.grafana.httpRoute.sharedGatewayNamespace }}
  hostnames:
    - {{ include "grafana.host" . }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        {{- if and .Values.grafana.authProxy.enabled .Values.grafana.authProxy.caddy.enabled }}
        - name: grafana-caddy
          port: 80
        {{- else }}
        - name: {{ .Values.grafanaChart.releaseName }}-grafana
          port: 80
        {{- end }}
{{- end }}
