{{- if .Values.crossplaneProviders.gf.enabled }}
apiVersion: dip.io/v1alpha1
kind: HelmApplication
metadata:
  name: provider-gf
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: {{ .Values.argocd.project }}
  source:
    repoURL: oci://ghcr.io/philips-software/helm-charts/crossplane-providers
    # renovate: datasource=github-releases depName=philips-software/helm-charts
    targetRevision: 0.0.26
    path: .
    helm:
      valuesObject:
        providers: [] # Disable default providers
        package:
          version: "v0.3.0"
          registry: "xpkg.upbound.io/loafoe"
        extraProviders:
          - name: provider-gf
            enabled: true
            debug: {{ .Values.crossplaneProviders.gf.debug }}
  destination:
    namespace: crossplane-system
  ignoreDifferences:
    - group: pkg.crossplane.io
      kind: DeploymentRuntimeConfig
      jsonPointers:
        - /spec/deploymentTemplate/spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 8
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}
