{{- if and .Values.spire.enabled .Values.spire.trustDomains }}
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: {{ include "pico-agent.fullname" . }}-federated
  labels:
    {{- include "pico-agent.labels" . | nindent 4 }}
spec:
  className: {{ .Values.spire.className | default "spire-release-spire" }}
  spiffeIDTemplate: "spiffe://{{ "{{" }} .TrustDomain {{ "}}" }}/ns/{{ "{{" }} .PodMeta.Namespace {{ "}}" }}/sa/{{ "{{" }} .PodSpec.ServiceAccountName {{ "}}" }}"
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ .Release.Namespace }}
  federatesWith:
    {{- range .Values.spire.trustDomains }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
