{{- if .Values.vpa.enabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "pico-agent.fullname" . }}-vpa
  labels:
    {{- include "pico-agent.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "pico-agent.fullname" . }}
  updatePolicy:
    minReplicas: {{ .Values.vpa.minReplicas }}
    updateMode: {{ .Values.vpa.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: {{ .Values.vpa.minAllowed.cpu }}
          memory: {{ .Values.vpa.minAllowed.memory }}
        maxAllowed:
          cpu: {{ .Values.vpa.maxAllowed.cpu }}
          memory: {{ .Values.vpa.maxAllowed.memory }}
        controlledResources: ["cpu","memory"]
{{- end }}
