apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: hsp-aws-platform-exception
  namespace: k8s-monitoring
spec:
  exceptions:
  - policyName: enforce-baseline-pod-security-profile 
    ruleNames:
    - enforce-baseline-profile
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - k8s-monitoring
        names:
        - k8s-monitoring-alloy-*
        - k8s-monitoring-beyla-*
  podSecurity:
    - controlName: "HostPath Volumes"
    - controlName: Capabilities
      images:
      - "*/grafana/alloy*"
      restrictedField: spec.containers[*].securityContext.capabilities.add
      values:
      - NET_RAW
    - controlName: "Privileged Containers"
      images:
      - "*/grafana/alloy*"
      restrictedField: spec.containers[*].securityContext.privileged
      values:
      - "true"