apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hsp-observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: HSP Managed Observabiltiy applications
  destinations:
    - name: in-cluster
      namespace: 'hsp-observability'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - hsp-observability
  sourceRepos:
    - https://github.com/philips-software/helm-charts
    - https://grafana.github.io/helm-charts
