cluster:
  name: {{ .Values.clusterName }}

destinations:
  - name: oltpGateway
    protocol: http
    type: otlp
    url: {{ .Values.otlp.gateway }}
    auth:
      type: basic
      usernameKey: "username"
      passwordKey: "apiKey"
    secret:
      create: false
      name: {{ .Values.otlp.secret.name }}
      namespace: {{ .Release.Namespace }}
    logs: { enabled: true }
    metrics: { enabled: true }
    traces: { enabled: true }

applicationObservability:
  enabled: true
  receivers:
    otlp:
      enabled: true
      http:
        enabled: true
      grpc:
        enabled: true

prometheusOperatorObjects:
  enabled: true

podLogs:
  enabled: true

traces:
  enabled: true

autoInstrumentation:
  enabled: {{ .Values.features.autoInstrumentation }}

alloy-metrics:
  enabled: true
  liveDebugging:
    enabled: true
  alloy:
    stabilityLevel: experimental

alloy-logs:
  enabled: true
  liveDebugging:
    enabled: true
  alloy:
    stabilityLevel: experimental
  controller:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: eks.amazonaws.com/compute-type
                  operator: NotIn
                  values:
                    - fargate

alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP