cluster:
  name: {{ .Values.clusterName }}

externalServices:
  prometheus:
    protocol: "otlphttp"
    writeEndpoint: "/"
    host: {{ .Values.otlpGateway | quote }}
    authMode: basic
    basicAuth:
      username: "otlp"
      passwordKey: "key"
    secret:
      create: false
      name: k8s-observability
      namespace: k8s-observability
  tempo:
    host: {{ .Values.otlpGateway | quote }}
    writeEndpoint: "/v1/traces"
    protocol: "otlphttp"
    authMode: basic
    basicAuth:
      username: "otlp"
      passwordKey: "key"
    secret:
      create: false
      name: k8s-observability
      namespace: k8s-observability
  loki:
    host: {{ .Values.otlpGateway | quote }}
    writeEndpoint: /loki/api/v1/push
    authMode: basic
    basicAuth:
      username: "admin"
      passwordKey: "key"
    secret:
      create: false
      name: k8s-observability
      namespace: k8s-observability

prometheus-operator-crds:
  enabled: false

opencost:
  enabled: false
  opencost:
    tolerations: []

configValidator:
  tolerations: []

kube-state-metrics:
  enabled: false
  tolerations: []

metrics:
  kube-state-metrics:
    enabled: false

traces:
  enabled: true

alloy:
  controller:
    replicas: 2
    tolerations: []

applicationObservability:
  enabled: true
  receivers:
    grpc:
      enabled: true

prometheusOperatorObjects:
  enabled: true

podLogs:
  enabled: true

alloy-metrics:
  enabled: true

alloy-logs:
  enabled: true
  controller:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: eks.amazonaws.com/compute-type
                  operator: NotIn
                  values:
                    - fargate


alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP

prometheus-node-exporter:
    enabled: false