{{- if and .Values.customAlloy.enabled .Values.customAlloy.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-custom-alloy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: custom-alloy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  targetRef:
    apiVersion: apps/v1
    {{- if .Values.customAlloy.clustering.enabled }}
    kind: StatefulSet
    {{- else }}
    kind: Deployment
    {{- end }}
    name: {{ .Release.Name }}-custom-alloy
  updatePolicy:
    updateMode: {{ .Values.customAlloy.vpa.updateMode | default "Auto" }}
  resourcePolicy:
    containerPolicies:
      - containerName: alloy
        controlledResources:
          - memory
        {{- with .Values.customAlloy.vpa.minAllowed }}
        minAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.customAlloy.vpa.maxAllowed }}
        maxAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
