apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: k8s-observability
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: k8s-observability
  source:
    chart: k8s-monitoring
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.6.0
    helm:
      releaseName: k8s-monitoring
      valuesObject:
        {{- (tpl (.Files.Get "config/k8s-monitoring-values.yaml") .) |  nindent 8 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: k8s-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
