apiVersion: v2
name: pico-agent
description: A lightweight Kubernetes helper service for webhook-triggered cluster operations
type: application
version: 0.43.0
appVersion: "v0.41.0"
keywords:
  - kubernetes
  - pvc
  - resize
  - spire
  - spiffe
home: https://github.com/loafoe/pico-agent
sources:
  - https://github.com/loafoe/pico-agent
maintainers:
  - name: Andy Lo-A-Foe
    email: andy.lo-a-foe@philips.com
