# Default values for fluent-bit-out-hsdp.

fluent-bit:
  extraVolumes:
    - name: plugins
      emptyDir: {}
  extraVolumeMounts:
    - mountPath: /out
      name: plugins
  initContainers:
    - name: copy-plugin
      image: philipssoftware/fluent-bit-out-hsdp-init:2.0.12
      command: ['cp', '/plugins/out_hsdp.so', '/out']
      volumeMounts:
        - mountPath: /out
          name: plugins
  command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf", "-e", "/out/out_hsdp.so"]
  config:
    outputs: |
      [OUTPUT]
          Name hsdp
          Match kube.*

      [OUTPUT]
          Name hsdp
          Match host.*
