fullnameOverride: alloy

tracing:
  filter_phi: true

alloy:
  stabilityLevel: "experimental"
  enableReporting: false
  clustering:
    enabled: true
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 473
    runAsGroup: 473
    seccompProfile:
      type: RuntimeDefault
  resources:
    requests:
      cpu: {{ .Values.alloy.resources.requests.cpu | default "100m" }}
      memory: {{ .Values.alloy.resources.requests.memory | default "500Mi" }}
    limits:
      cpu: {{ .Values.alloy.resources.limits.cpu | default "200m" }}
      memory: {{ .Values.alloy.resources.limits.memory | default "1Gi" }}
  configMap:
    key: "config.alloy"
    content: |- {{- (tpl (.Files.Get "config/config.alloy") .) | trim | nindent 6 }}
  extraArgs: {{ .Values.alloy.extra_args }}
  extraPorts:
    - name: "faro"
      port: 12347
      targetPort: 12347
      protocol: "TCP"
    - name: "otlpgrpc"
      port: 4317
      targetPort: 4317
      protocol: "TCP"
    - name: "otlphttp"
      port: 4318
      targetPort: 4318
      protocol: "TCP"
  mounts:
    extra:
      - name: "api-key"
        mountPath: "/var/lib/api-key"

controller:
  type: "statefulset"
  volumes:
    extra:
      - name: "api-key"
        secret:
          secretName: {{ .Values.api_key.secret | quote }}
          key: key
  priorityClassName: system-node-critical
  enableStatefulSetAutoDeletePVC: true
  autoscaling:
    enabled: true
    minReplicas: {{ .Values.controller.autoscaling.min_replicas | default 1 }}
    maxReplicas: {{ .Values.controller.autoscaling.max_replicas | default 3 }}
    targetCPUUtilizationPercentage: {{ .Values.controller.autoscaling.utilization.cpu | default 80 }}
    targetMemoryUtilizationPercentage: {{ .Values.controller.autoscaling.utilization.memory | default 80 }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.controller.autoscaling.scaledownwindow | default 300 }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.controller.autoscaling.scaleupwindow | default 10 }}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key : "eks.amazonaws.com/compute-type"
                operator : NotIn
                values:
                  - fargate
