{{/*
Expand the resource prefix.
*/}}
{{- define "masterdata-datasource.resourcePrefix" -}}
{{- required "A valid environmentConfig.resourcePrefix entry required!" .Values.environmentConfig.resourcePrefix -}}
{{- end -}}

{{/*
Common labels
*/}}
{{- define "masterdata-datasource.labels" -}}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}

{{/*
Name of the secret holding host/port/username. Defaults to the secret generated by the
Postgres CR; when using an existing database, points at the user-supplied secret.
*/}}
{{- define "masterdata-datasource.connectionSecretName" -}}
{{- if .Values.postgres.useExisting -}}
{{- required "postgres.existing.connectionSecretName is required when postgres.useExisting is true" .Values.postgres.existing.connectionSecretName -}}
{{- else -}}
{{- printf "%s-masterdata-connection-details" (include "masterdata-datasource.resourcePrefix" .) -}}
{{- end -}}
{{- end -}}

{{/*
Name of the secret holding the database password.
*/}}
{{- define "masterdata-datasource.passwordSecretName" -}}
{{- if .Values.postgres.useExisting -}}
{{- required "postgres.existing.passwordSecretName is required when postgres.useExisting is true" .Values.postgres.existing.passwordSecretName -}}
{{- else -}}
{{- printf "%s-masterdata-password" (include "masterdata-datasource.resourcePrefix" .) -}}
{{- end -}}
{{- end -}}

{{/*
Key lookups within the connection/password secrets. When using an existing database the keys
are configurable; otherwise they match the keys written by the Postgres CR.
*/}}
{{- define "masterdata-datasource.hostKey" -}}
{{- if .Values.postgres.useExisting -}}{{ .Values.postgres.existing.connectionSecretKeys.host | default "host" }}{{- else -}}host{{- end -}}
{{- end -}}
{{- define "masterdata-datasource.portKey" -}}
{{- if .Values.postgres.useExisting -}}{{ .Values.postgres.existing.connectionSecretKeys.port | default "port" }}{{- else -}}port{{- end -}}
{{- end -}}
{{- define "masterdata-datasource.usernameKey" -}}
{{- if .Values.postgres.useExisting -}}{{ .Values.postgres.existing.connectionSecretKeys.username | default "username" }}{{- else -}}username{{- end -}}
{{- end -}}
{{- define "masterdata-datasource.passwordKey" -}}
{{- if .Values.postgres.useExisting -}}{{ .Values.postgres.existing.passwordSecretKey | default "password" }}{{- else -}}password{{- end -}}
{{- end -}}
