name: Helm Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  helm:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push the Helm Charts to GitHub Container Registry
        uses: ./.github/actions/action-helm-chart-repo
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          chartsPath: ./charts/
